name: Auto commit for fun

on:
  schedule:
  - cron: '15 4,8,15 * * 0-2'
  - cron: '0 8-20 * * 1-5'
  - cron: '10 3-11 4-20 * *'

jobs:
  auto_commit:
    name: 'Auto push a commit to my repo'
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Create sample file with just timestamp
      run: date +%s >> report.txt
    - name: Commit file
      run: |
          git config --global user.name 'Nguyen Huu Nguyen Y'
          git config --global user.email 'imrim12@users.noreply.github.com'
          git add report.txt
          git commit -am "chore: update automated report for fun"
          git push
